### ISSUE TITLE
Node Red

### ISSUE THREAD

**Issue by brian-burton** [bennuttall/hello-world-raspberry-pi#2]
This flow injects the string "Hello world" into the debug tab.

`[{"id":"5e433d93.f63b84","type":"inject","z":"5458c33a.6eeebc","name":"Inject the string \"Hello world\"","topic":"","payload":"Hello World","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":240,"y":140,"wires":[["46376d11.ca318c"]]},{"id":"46376d11.ca318c","type":"debug","z":"5458c33a.6eeebc","name":"Output to debug tab","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","x":500,"y":140,"wires":[]}]`

Copy the whole json object to the clipboard, then from the menu (hamburger, top right) select `Import` then `Clipboard` and paste in. Place it, deploy it, then click the left touch point on the inject node.

The screenshot is from my desktop PC, but NodeRed itself is running on a Raspberry Pi 1 B, as installed in vanilla Raspbian desktop.

![nodered_helloworld](https://user-images.githubusercontent.com/10343998/37486685-2693ddd8-2887-11e8-938e-688e5aad6c18.png)

To recreate yourself, do the following:

1. Drag an `Inject` node to the main flow.
2. Double click it to edit. Change the `Payload` dropdown to the type `string`, then type `Hello world` in the `Payload` box. Click `Done`.
3. Drag a `Debug` node to the main flow.
4. Click and drag a wire from the output of the `Inject` node to the input of the `Debug` node.
5. Click `Deploy` in the top right of the window.
6. Click the touch point on the left of the `Inject` node to write `Hello World` in the debug tab (you may need to click on the `Debug` tab if it is not selected).

**Comment by dceejay** [comment]
Bonus points for adding the play-audio node and making it say Hello World as well. (if you plug in a speaker)

**Comment by cymplecy** [comment]
I'd change the order around so that the re-create instructions become the main intructions as I think that's what's Ben is looking for

Probably actually miss off the internal code entirely

**Comment by cymplecy** [comment]
And keep it dead simple by just assuming its running on localhost .e.g start Node-RED - launch browser - type in localhost:1880

**Comment by brian-burton** [comment]
@dceejay I could earn those bonus points, but I have so many unfinished projects I'm gonna declare "sign up for a text to speech API key" as boilerplate and back slowly away... ;-)

**Comment by cymplecy** [comment]
This would be my suggested mod to the above

# Node-RED

1. Open **Node-RED** from Programming in the main menu

1. Open **Chromium Web Browser** from Internet menu (or click icon at top)

1. Drag a blue `Inject` node from the list of nodes on the left, into the main flow workspace area

1. Double-click on it and change `Payload` from timestamp to string and type in Hello World and then click `Done`

1. On the left pane, scroll down to green `Debug` and drag that out to the right of the Inject node

1. Double-click on it and click to enable node status -  press `Done`

1. Click and drag a wire from the output of the `Inject` node to the input of the `Debug` node.

1. Click `Deploy` in the top right of the window.

1. Click the button on the left of the `Inject` node to see Hello World appear beneath the `Debug` node (you can also see it if you click on the `Debug tab`)  
![capture](https://user-images.githubusercontent.com/2357428/37516101-f303dfd0-2904-11e8-9128-4e7d2f144b7f.PNG)

**Comment by dceejay** [comment]
the play audio node uses in-browser tts - no key needed - just the node....  - but yeah - adding a third node is going too far :-)

**Comment by bennuttall** [comment]
Sorry, it's no longer in Raspbian by default
